language: java

addons:
  sonarcloud:
    organization: "zbrainiac"
    token:
      secure: "Qt2y78B5CXP3t8QGOCYOnRcW5jmw07kWPASfTdM/jCUmajtT+NBGEE2O/gCY51yDuVAJGJamo7rrA9zPlJ/cKAHvYTHg+onFlJjlMnRsMC8mpAA8OeqxLRrSud4p/QHGCvhiuB0aaqp2QcIS0tBlUDJa8L7xaMKOE99f8D1Ma/V2lkyO0hWi78pOBLZP54HNI13JA+VXYBGz5GLWzOqe7UMfVL3GuEFFIxsv6TIg/ULI2th0icXQBDvXcWtPIWmv6CN+3XOiVUDlZwlWR5DTosj2NU9W/Ld1HJxafcai8V022dNuMIAqHIOwiWiaI+4VEX6MKKkIS/NwEg4q922Yx8PaDjY16WqAbDHTSfDYxKZYBV+IN2pcpA4biGgAb29lidMSCwTWorTRiJa0idl/SQnXLYwwGAwuml2wwfBf7NfrLog56TzJ+arU/LkHe0Qrgb9dH+nYMgu14HLODx9juusia/zU+B/x3QfP81EgKZ6Q6FA0L6rr3L283KTSBTpgKr2xJWhJ+DPSwGx3OtF6KwZKYgILs1H7B2S9HZJORGLaaC3c0BJw8TDsMEgSx7wTsBhj7VRKovJG19YtosFdSIwkHT5e8dJnvhkJa/y+5TkjLzM349YS9ChltUy2TkHUDq0ZIS0CWZq2kPF89moJDTlXQbS876BUhq2EMAcO8rk="

script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar
