language: java
addons:
  sonarcloud:
    organization: "zbrainiac"
    token:
    secure: "W8EbRNRfkJvKmtAlyyruyvCl+mcwAgYK68224OZYKLTjNzLN93B+sJtU/HY59j/0w2MKDQCOEZ8OuXX2wR4HMmKxf3LQh6FmVZ9sUXzyB9uVghs3v8DyVmWQWlwKWKNZ5BxAKgaGJEv8l+D41RUA9//HlGZpQRx2Monreqq2azQyYeYnnxRZzxR2qlSY4qbt1BfWP0rY+VWLkwa66s2/2HCLKUojFtf3Ov666eRSvn1sSAWusEcJLPzE4OTCgY3/Vv9WqJSy+q7JNR2uCTcI8Zd1LY/VH+yGpArhha8wo7k9jIMp8jfk9wPhPdtld+t7s0p9BRUaFQM1MfVtCj29QxEh3XdS+sB/9iTS9oyu3hJr0BsR2oj6gBdp5QLjp0okC99/Y8Y+muqZLEvd0LdOhgh4HdeIY+RiE3lFLesjIYMlVzHZG3El00hw7YAaVGxjamr+Bl+OLsSnSVWwe7oGszcASayyjSKKVY99JGtY4ywS9SLG5r265LK/Qy9mASTwF0/0+5DdsusS+YbbABsRNLfGTq66vGoJfTGONDLa5RK2/9pP0FK9nqeAgOYMi8LMa/8mNEaEsDEsWiPaDQNAlxQ7uHlsRK+63jAuyERi7GEO1coj8shrDqlYVBDKFyDA5xhJ5RgzEUgugSv3kT06q2psjwE0ZZ9vua34UAc7hwE="

script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar